AllCops:
  TargetRubyVersion: 2.4.4
  Exclude:
    - spec/fixtures/**/*

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
