AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - spec/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

Bundler/GemVersion:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/TopLevelMethodDefinition:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
