AllCops:
  TargetRubyVersion: 2.4.4
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - spec/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
